version: "3.4"
services:
  frontend:
    container_name: frontend
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true